<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="chrome"
           tests="6"
           failures="1"
           errors="0"
           skipped="4"
           time="16.485">
  <properties />
            <testcase name="Login" time="16.484" classname="com.trantor.suppliermanagementtest.AddASupplierIndustryTest">
                <failure type="java.lang.AssertionError"
                  message="User is not able to login successfuly"
              >
<![CDATA[java.lang.AssertionError: User is not able to login successfuly
  org.junit.Assert.fail(Assert.java:88)
  org.junit.Assert.assertTrue(Assert.java:41)
  org.trantor.ems.Login_Test.Validlogin(Login_Test.java:31)
  com.trantor.suppliermanagementtest.AddASupplierIndustryTest.Login(AddASupplierIndustryTest.java:48)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
      </failure>

          </testcase>
  
            <testcase name="VerifySupplierIndustryPage" time="0.0" classname="com.trantor.suppliermanagementtest.AddASupplierIndustryTest">
          <skipped />
    </testcase>
            <testcase name="VerifyCancelbuttonDeleteIndustry" time="0.0" classname="com.trantor.suppliermanagementtest.AddASupplierIndustryTest">
          <skipped />
    </testcase>
            <testcase name="VerifyAddNewIndustry" time="0.0" classname="com.trantor.suppliermanagementtest.AddASupplierIndustryTest">
          <skipped />
    </testcase>
            <testcase name="VerifyDeleteIndustry" time="0.0" classname="com.trantor.suppliermanagementtest.AddASupplierIndustryTest">
          <skipped />
    </testcase>
  
            <testcase name="Initialize" time="0.001" classname="com.trantor.suppliermanagementtest.AddASupplierIndustryTest" />
      
</testsuite>
